version: '3'

services:

  app:
    container_name: fastapi-develop
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/fastapi.dockerfile
      args:
        - PG_PASSWORD=${POSTGRES_PASSWORD}
        - PG_USER=${POSTGRES_USER}
        - PG_DB_NAME=${POSTGRES_DB}
        - PG_DB_PORT=${POSTGRES_PORT}
    networks: 
      - custom_network_1
   
    environment:
      - POSTGRES_SERVER=db
    ports:
      - 80:80
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - psql_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks: 
      - custom_network_1 

  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
        - "1112:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_LOGIN}
        PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWD}
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks: 
      - custom_network_1 
  dbcreate:
    container_name: dbcreate
    image: dbcreate:latest
    build: 
      context: ../source/
      dockerfile: ../docker/dockerfiles/dbcreate.dockerfile
      args:
        - PG_PASSWORD=${POSTGRES_PASSWORD}
        - PG_USER=${POSTGRES_USER}
        - PG_DB_NAME=${POSTGRES_DB}
        - PG_DB_PORT=${POSTGRES_PORT}
        - REDIS_PASSWD=${REDIS_PASSWORD}
    networks: 
      - custom_network_1
    depends_on:
      - db
     

networks:
  custom_network_1:
volumes:
  pgadmin:
  psql_volume:               













    # networks:
      # custom_network_1:
      # node_net:
        # ipv4_address: 172.28.1.4

# networking for the Redis container

#   node_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.0.0/16
